### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by AmirHosseinAsa** [hassan-sd/sd-video-install#5]
I installed Torch using the following command:
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.8 -c pytorch -c nvidia
However, I encountered an error in Streamlit after clicking on "Load Model".

![Screenshot 2023-12-04 080521](https://github.com/hassan-sd/sd-video-install/assets/92585902/9f38bdfc-ad34-4cb8-8116-bb3b9390cc46)

**Comment by KarhellTwitch** [comment]
I resolved this issue by launching the venv in a cmd and: `pip uninstall torch` and then using `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121` instead (i have cudatoolkit 12.1 installed on my computer)
However torchvision and torchaudio are optional in this command i think. If you have cudatoolkit 11.8 simply replace 121 by 118 in the url
